# Create new swarm with app db and webserver and remote storage through nfs
version: "3.2"
services:
  db_server:
    image: 172.16.169.226:5000/mydb
    networks:
      - blog_network
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
    volumes:
      #- database_volume:/data/db
      - type: volume
        source: dbvol
        target: /data/db
      - type: volume
        source: dbvol
        target: /data/configdb
  app_server:
    image: 172.16.169.226:5000/myapp
    networks:
      - blog_network
    depends_on:
      - db_server
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  webserver:
    image: 172.16.169.226:5000/mywebserver
    networks:
      - blog_network
    ports:
      - 8080:80
    depends_on:
      - app_server
    deploy:
      replicas: 3 
      restart_policy:
        condition: on-failure
networks:
  blog_network:

volumes:
  dbvol:
    driver: local
    driver_opts:
      type: nfs
      o: 'addr=172.16.169.226,rw,nolock'
      device: ':/var/nfs/dbvol'
   #database_volume:
